# Generated by Django 6.0.5 on 2026-06-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='mascota',
            name='edad',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='mascota',
            name='tamano',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
